version: "1.1"
services:
  api:
    image: back
    container_name: back
    build: 
      context: ./BackEndSide
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    networks:
      - app-network
      
  front:
    image: web
    container_name: web
    build: 
      context: ./FrontEndSide
      dockerfile: ./dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - api
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - api
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge