FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN npm install
# Then we install serve. It helps you serve a static site, single page application or just a static file.
RUN npm i -g serve
COPY . .
# We ran npm run build to create a production build of our application.
RUN npm run build  
EXPOSE 3000
# The last command serve -s distruns only when the container spins up. It is not part of the Image creation process.
CMD [ "serve", "-s", "dist" ] 
