# first shot
# FROM node:23-alpine
# WORKDIR /app
# COPY package.json .
# COPY ./ ./
# RUN npm install
# RUN npm run build
# # EXPOSE 3001
# # EXPOSE 5173
# CMD [ "npm", "run", "dev" ]

# second shot
# Build Stage
# FROM node:18-alpine AS build
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build
 
# # Production Stage
# FROM nginx:stable-alpine AS production
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

# third shot
FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN npm install
# Then we install serve. It helps you serve a static site, single page application or just a static file.
RUN npm i -g serve
COPY . .
# We ran npm run build to create a production build of our application.
RUN npm run build  
EXPOSE 3000
# The last command serve -s distruns only when the container spins up. It is not part of the Image creation process.
CMD [ "serve", "-s", "dist" ] 
